name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile (optional)
        run: echo "No linting step defined"

      - name: Build Docker image
        run: docker build -t myapp:test .

      - name: Run tests (optional)
        run: echo "No test step defined"
